import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <div className="flex flex-col min-h-screen">
      <header className="p-4 bg-blue-500 text-white flex justify-between items-center">
        <div className="text-xl font-bold">Ares by Dataminds</div>
        <nav>
          <ul className="flex space-x-4">
            <li>
              <Link href="/about" className="hover:text-gray-300">About Us</Link>
            </li>
            <li>
              <Link href="/login" className="hover:text-gray-300">Log In</Link>
            </li>
            <li>
              <Link href="/signup" className="hover:text-gray-300">Sign Up</Link>
            </li>
          </ul>
        </nav>
      </header>
      <body className={inter.className}>{children}</body>
    </div>
      
    </div>
  )
}
